### ISSUE TITLE
Advanced CSS Support

### ISSUE THREAD

**Issue by gabelerner** [gabelerner/canvg#217]
_From [brett.la...@brettlaforge.com](https://code.google.com/u/102858262865343733540/) on March 21, 2013 17:49:05_

What steps will reproduce the problem? 1. <svg>
  <style type='text/css'>
    <![CDATA[
      .parent rect { fill: red; }
    ]]>
  </style>
  <g class="parent">
    <rect x='10' y='10' width='25' height='15' />
  </g>
</svg> What is the expected output? What do you see instead? I expected to see a red rectangle. Instead I get a blank canvas.

_Original issue: http://code.google.com/p/canvg/issues/detail?id=217_

**Comment by RafiKueng** [comment]
post to keep getting updates. I posted the hackish solution in Issue 127

**Comment by gabelerner** [comment]
closed with https://github.com/gabelerner/canvg/pull/317
