### ISSUE TITLE
unable to replicate in canvas (css)

### ISSUE THREAD

**Issue by kudoslabs** [gabelerner/canvg#337]
please see this http://jsfiddle.net/ezk3Lgzs/7/
and this stack issue http://stackoverflow.com/questions/28600801/svg-to-canvas-with-canvg-not-respecting-css

could you give an example of how to insert the inline css to this example so it will center align and match

**Comment by Gnafu** [comment]
:+1: 
Confirm that css styles are ignored.
My use case is the "canvg-ing" of a [MetricsGraphic](http://metricsgraphicsjs.org/) chart

**Comment by gabelerner** [comment]
canvg will probably never support html styles like "margin: 0 auto" because i'm keeping it minimal to rendering svgs outside of another context ... here, i'd have to support all the dom styles which would extend my lib to support both svg and html which isn't in the plans
