### ISSUE TITLE
canvg seems to render tspan in patterns twice

### ISSUE THREAD

**Issue by Toushin** [gabelerner/canvg#348]
See this fiddle: https://jsfiddle.net/Toushin/1c5x0n0v/12/

I don't see any problems in my SVG, but on the canvas the tspans in the pattern are rendered twice.

This fiddle is the result of trying to build a workaround for issue https://github.com/gabelerner/canvg/issues/342 .

**Comment by maciejjankowski** [comment]
seems related to https://github.com/gabelerner/canvg/issues/347

**Comment by LoufL** [comment]
I also had this problem and found a stackoverflow question about it that helped me found a dirty fix for it, see here : http://stackoverflow.com/questions/28563073

**Comment by gabelerner** [comment]
closing this as the fiddle is now lookin good ... fixed by https://github.com/gabelerner/canvg/pull/340
