### ISSUE TITLE
<image> tag causes error in firefox

### ISSUE THREAD

**Issue by tomarcafe** [gabelerner/canvg#349]
export to canvas works ok for me, thank you for the software.

but <image> causes error when trying in firefox, no matter &lt;image / &gt; or &lt;image&gt;&lt;/image&gt; is used.
errors in can be different -so far i saw
 'prefix not bound to namespace' (and it points to <!DOCTYPE html> when i click the error message), 
and 'no closing tag, expected </link>' or so (and it points just before </head> closing tag then)

it seems that for some reason firefox starts to parse whole window dom tree when it encounters <image> in target svg (and it fails for html5 doc, which is ok). when i remove <image>, export works ok in firefox. in chromium it works finr.

generated svg originates from following template: 

        <svg xmlns="http:// www.w3.org/2000/svg"
         class="field {{selectedName}}-field {{#if rotated}}viewport_90cw{{/if}}"
         viewBox="{{#if rotated}}{{y}} {{x}} {{h}} {{w}}{{else}}{{x}} {{y}} {{w}} {{h}}{{/if}}"
         data-id="{{id}}" id="{{name}}">

        <g class="field" transform="{{#if rotated}}rotate(90, 0, 0){{/if}}">
            {{#if fieldImage}}
                <image xlink:href="{{fieldImage.url}}" x="{{x}}" y="{{y}}"
                       width="{{w}}" height="{{h}}">
                </image>{{/if}}
        </g>
        <g class="players">{{> Players rotated=rotated players=_players }}</g>
    </svg>

it produces xlink:href in relative form ('/img/image.jpg'), yet same result i saw when used absolute url

**Comment by DorianGrey** [comment]
We've also encountered this problem - and by taking a closer look at the svg, it seems that the explicit declaration of xlink is missing in the svg node:

    xmlns:xlink="http://www.w3.org/1999/xlink"

Dunno why it is missing, but if it is added manually before forwarding the node, if works fine - at least for data URLs. Maybe you can check if this works in you case as well?

We've also faced this in various versions of IE and Safari; funny to see that it works without this attribute in Chrome/Chromium - it should not.

**Comment by gabelerner** [comment]
the current master allows for 'href' or 'xlink:href'

**Comment by ravend7** [comment]
Hi!
Why convert <image> does not work?
work:
http://jsfiddle.net/L3hondLn/301/
don't work:
http://jsfiddle.net/L3hondLn/300/
