### ISSUE TITLE
Regex error in IE 8

### ISSUE THREAD

**Issue by beingmrkenny** [gabelerner/canvg#351]
On line 116 on canvg.js, there is a replace call:

    selector = selector.replace(/{[^]*/gm, ' ');

The regex here does not appear to be a valid regex, though I may be mistaken. In any case, in IE8 this causes canvg to crash.

**Comment by PallabDV** [comment]
This is a showstopper for using this library in a project which could be used in IE 8.

**Comment by gabelerner** [comment]
what's the valid ie8 version of this? if you open a PR with something that continues to work on modern browsers, i'll merge it

**Comment by beingmrkenny** [comment]
Hi,

Sorry for late reply/stupid question, but what do you mean the valid ie8 version? Do you mean what regex works in IE8? If so, my fix was to remove the line.

Is this a real regex? There's two things I don't understand: one is the `{` character which doesn't have a partner, and the second is the `[^]*` — Seems to be matching 0 or more "anything that's not" characters but doesn't specify what the characters are not.

Since I couldn't work out what this regex was for, I just removed the line instead of trying to fix it.
