### ISSUE TITLE
Project has no package versions / git tags

### ISSUE THREAD

**Issue by visby** [gabelerner/canvg#353]
Currently the repository has no tags, which prevents referencing specific versions of canvg using bower.
Bower dependencies can be versioned by creating git tags.

**Comment by momerlin** [comment]
+1

**Comment by lastboy** [comment]
The current bower result is pointing to the old one..

bower not-cached    https://github.com/shprink/canvg.git#*
bower resolve       https://github.com/shprink/canvg.git#*
bower download      https://github.com/shprink/canvg/archive/v1.3.0.tar.gz
bower extract       canvg#* archive.tar.gz
bower resolved      https://github.com/shprink/canvg.git#1.3.0
bower install       canvg#1.3.0

**Comment by visby** [comment]
@lastboy See also https://github.com/shprink/canvg/issues/1

**Comment by gabelerner** [comment]
https://github.com/gabelerner/canvg/releases/tag/v1.0

**Comment by michalvvv** [comment]
+1
