### ISSUE TITLE
Don't crash while rendering MISSING elements

### ISSUE THREAD

**Issue by LarsWeber** [gabelerner/canvg#355]
inside the renderChild function check if the element is unknown and don't try to render it:

canvg.js:2123,7

    this.renderChild = function(ctx, parent, i) {
        var child = parent.children[i];
        if (child instanceof svg.Element.MISSING) {
            return;
        }
        if (child.attribute('x').hasValue()) {

**Comment by gabelerner** [comment]
do you have an SVG example of what breaks?

```svg
<svg><blah /></svg>
```

doesn't throw an js errors for example

**Comment by rik-v** [comment]
I had this issue with filters, putting a filter in like this will cause a crash:
```html
<!-- see: http://www.w3schools.com/svg/tryit.asp?filename=trysvg_feoffset3 -->
<defs>
  <filter id="f1" x="0" y="0" width="200%" height="200%">
    <feOffset result="offOut" in="SourceAlpha" dx="20" dy="20" />
    <feGaussianBlur result="blurOut" in="offOut" stdDeviation="10" />
    <feBlend in="SourceGraphic" in2="blurOut" mode="normal" />
  </filter>
</defs>
```
feOffset and feBlend are not implemented, therefore a crash will occur.
In my case the problem presented itself at: canvg.js, line:2647.
replacing this:
```javascript
for (var i = 0; i < this.children.length; i++)
{
    this.children[i].apply(tempCtx, 0, 0, width + 2 * px, height + 2 * py);
}
```
with this:
```javascript
for (var i = 0; i < this.children.length; i++)
{
    if (this.children[i] instanceof svg.Element.MISSING) continue;
    this.children[i].apply(tempCtx, 0, 0, width + 2 * px, height + 2 * py);
}
```
fixes this issue.
I did not run into this with other elements, but my svg markup was very simple in this case (just a plain circle, that's it)
