### ISSUE TITLE
Using base64 image as svg image pattern not working

### ISSUE THREAD

**Issue by ParHaggstrom** [gabelerner/canvg#357]
**Background:** Im ajax fetching an svg and rewriting parts of it before drawing it using Canvg, among other things changing the pattern with an image of my own choosing

**Result:** *Image not found* error in Firefox and a *strange red fill* is generated in Chrome

**Comment by gabelerner** [comment]
i don't have control over how the images are loaded ... i create an html image (https://github.com/gabelerner/canvg/blob/master/canvg.js#L2346) then use canvas context drawImage to render it (https://github.com/gabelerner/canvg/blob/master/canvg.js#L2375) ... it works in most cases, but it appears that most likely the browser just doesn't support what you want to do.  do you have your svg string w/ the base 64 pattern so i could debug further?

**Comment by ParHaggstrom** [comment]
Think your spot on there. Tried recreating the problem after I solved it with another approach but couldn't trigger the problem again so guess its very specific loading issue when the image hasn't had time to load when rendering. I'm closing the issue, thanks for looking into it!
