### ISSUE TITLE
Save object svg  сreated Raphaël

### ISSUE THREAD

**Issue by wolf002** [gabelerner/canvg#370]
Library fine saves by using objects in Raphaël in
Tested browsers such as  in Chrome, Firefox, Opera, and IE (through FlashCanvas)
But Safari 5 we must find href instead :href this small hack allow us save image fine
```javascript
			this.getHrefAttribute = function() {
				for (var a in this.attributes) {
					if (a.match(/:href$/) || a.match(/href$/) ) {
						return this.attributes[a];
					}
				}
				return svg.EmptyProperty;
			}
```
In safari 7 and chrome running ios problem occurs in the place
```javascript
				var parser = new DOMParser();				
				return parser.parseFromString(xml, 'text/xml');
```
because Raphaël generates images in such a way
```<image x="0" y="0" width="11" height="37" preserveAspectRatio="none" NS1:href="59.png"></image>
<image x="0" y="0" width="11" height="37" preserveAspectRatio="none" NS2:href="60.png"></image>```
and it is necessary
```<image x="0" y="0" width="11" height="37" preserveAspectRatio="none" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="59.png></image>
<image x="0" y="0" width="11" height="37" preserveAspectRatio="none" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="60.png></image>```
I solved this problem by simply changing of the line, and then the results obtained, put to the canvg
```javascript
            for(i=0;i<40;i++){
                svg = svg.replace("NS"+i,'xmlns:xlink="http://www.w3.org/1999/xlink" xlink'); 
            }
```
And it solved the problem.
I hope that my post will be useful to someone thread, and the author will take into account these changes in your code.

**Comment by Krokador** [comment]
I realize this is an old issue, but is is still current this solution has actually just saved us while trying to save an svg to png on safari for mac, and I figured I would add that we had a similar issue with textPath elements. Safari's DOMParser would just hiccup at the first encounter of an "invalid" image/textPath tag (which it generated itself. Why would Apple not want to safely parse their own DOM without issues, I have no clue) and return us a single white rectangle, leaving us with a "blank" image and leaving us puzzled the eff out. 

Funnily enough, Safari for windows (however old it is), does not have this issue.

Anyways, the fix ended up being as follows (I think the regex way is much more scalable):

```
//images are generated with NS{9} instead of xlink like other browsers... not sure why, but this fixes it
svg = svg.replace(/(NS|ns)\d+:href/g, 'xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href');
//safari's DOMParser also cannot handle textPaths the way they are generated IN SAFARI (missing the xmlns link there, too)
svg = svg.replace(/\<textPath xlink:href/g, '<textPath xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href'); 
```
(we have integrated textPaths with one of the pull requests on the repository here. Seems to work really well and i was even able to modify the code to handle css text-transforms, I just haven't gotten around to add it to the git here)
