### ISSUE TITLE
blurry on retina display

### ISSUE THREAD

**Issue by btm1** [gabelerner/canvg#379]
If converted on a retina display or high resolution display of any kinda the image is blurry.

**Comment by gabelerner** [comment]
you should enlarge your SVG size then and render it with scaleWidth/scaleHeight options through canvg to get the resolution you desire.

**Comment by chpio** [comment]
@gabelerner
why should i set the scaleWidth/scaleHeight options if i already have to enlarge the svg?
setting just the scaleWidth/scaleHeight options makes the output blurry:
```javascript
const canvas = document.createElement('canvas');
canvas.width = 600; // svgWidth * 2
canvas.height = 840; // svgHeight * 2
canvg(
  canvas,
  svgText, {
    ignoreDimensions: true,
    scaleWidth: canvas.width,
    scaleHeight: canvas.height,
  }
);
```

**Comment by gabelerner** [comment]
@chpio maybe i misinterpreted the original question.

if i understand correctly, something that looks good on retina is something that has high dpi.  to achieve that here,  i think you start with a large canvas that you render an svg to, and then scale the canvas down with width/height before displaying it back to the user.  

if i'm still confused, maybe a more explicit example will help? i have a mac so should be able to test quite easily.
