### ISSUE TITLE
How to set static canvas width/height?

### ISSUE THREAD

**Issue by mato75** [gabelerner/canvg#382]
<canvas id="canvas" width="1020px" height="768px" style="position: fixed; top: 0px; left: 0; display: inherit"></canvas>

I have in svg height and width. This changes the height and width of canvas. Now if I set width and height with javascript afterwords, the canvas is empty.

**Comment by gabelerner** [comment]
if you read the readme, you can set `ignoreDimensions: true` to not resize the canvas. if you do resize it with javascript, you can pass in `forceRedraw` to redraw after ever resize:

```javascript
var resized = false;
window.resize = function () {
  resized = true;
};

canvg(..., {
  ignoreDimensions: true,
  forceRedraw: function() {
    if (resized) {
      resized = false;
      return true;
    }
    return false;
  }
});
```
