### ISSUE TITLE
XML5632 in IE 11

### ISSUE THREAD

**Issue by antiremy** [gabelerner/canvg#386]
Whenever I would attempt use canvg on a div that contained two charts, it would work fine in both Chrome and Firefox but Internet Explorer 11 would stop and throw "XML5632: Only one root element is allowed." After a bit of researching, I realized that IE won't allow you to have two <svg> (in this case root)  tags in the XML string. So to fix this, I simply put

        var findSecondRoot = xml.indexOf("<svg", xml.indexOf("<svg")+1);
        xml = xml.substring(0, findSecondRoot);
at the beginning of the svg.parseXml function, before the if statement.

I'm just putting this up for reference because I couldn't find a solution on my own.

EDIT: On second thought, you could also use this to simply fix your content before passing it to canvg. It doesn't necessarily have to be in canvg.js

**Comment by gabelerner** [comment]
canvg will only support a single root for now. as you said, you can just fix the content. one easy way is to just wrap everything in an `<svg>...</svg>` since the `svg` tag can be nested into itself.
