### ISSUE TITLE
multi-space sequence in text element is collapsed to a single space

### ISSUE THREAD

**Issue by xr250** [gabelerner/canvg#391]
Sample SVG is below. Browsers render the text element with the multiple space sequence intact. canvg collapses it to a single space. 

![image](https://cloud.githubusercontent.com/assets/13562554/8972059/9bb33104-3613-11e5-99df-b8702e2fb3d2.png)

<svg xmlns="http://www.w3.org/2000/svg" width="640" height="480">
  <rect id="svg_4" height="100" width="400" y="12" x="16" stroke-width="5" stroke="#000000" fill="#ffff00"/>
  <text xml:space="preserve" text-anchor="middle" font-family="serif" font-size="100" id="svg_3" y="92" x="200" stroke-width="0" stroke="#000000" fill="#000000">A        A</text>
</svg>

**Comment by gabelerner** [comment]
i'm pretty sure svg is treated like html where spaces are collapsed.  please reopen after updating this http://jsfiddle.net/L3hondLn/391/ with something that shows a difference
