### ISSUE TITLE
JSPM loading error

### ISSUE THREAD

**Issue by samouss** [gabelerner/canvg#393]
Hello,

I have trouble for loading `canvg` with JSPM.

I have read this issue #316 and it seems to work. But at this time the module was anonymous, this commit b90008dcfaf1104d1cb6b372d8939341fca59e94 gives a name to the module.

If I remove the module name it works, I don't think it's a JSPM problem because others modules are named (like jQuery). But maybe I'm wrong.

Any ideas ?

Thanks.

**Comment by MikeJoyce19** [comment]
I am having the same problem. Removing this change results fixes the error.

**Comment by gabelerner** [comment]
i don't really have the bandwidth to test every loader out there ... if I remove https://github.com/gabelerner/canvg/commit/b90008dcfaf1104d1cb6b372d8939341fca59e94, does the require JS error come back and is there another way to fix it to allow JSPM to work @zky829 ?

**Comment by MikeJoyce19** [comment]
This might be a JSPM issue. Issue https://github.com/systemjs/systemjs/issues/682 Created to address this

**Comment by samouss** [comment]
Okay thanks a lot for these informations.

**Comment by MikeJoyce19** [comment]
FYI the above SystemJS issue was fixed and closed
