### ISSUE TITLE
Nothing renders if any element has an attribute containing "<" or ">"

### ISSUE THREAD

**Issue by seangibat** [gabelerner/canvg#403]
Try using canvg on any svg with an element inside it anywhere with an attribute containing a `<` or a `>`. I found this when I had a 'title' attribute that contains such characters, but even a made up HTML attribute like `test='e<e' `will do this.

**Comment by gabelerner** [comment]
that's invalid html ... need to use `&gt;` or `&lt;`

browsers won't even allow this
```
This page contains the following errors:
error on line 1 at column 33: Unescaped '<' not allowed in attributes values
```
