### ISSUE TITLE
tspan not rendering correctly when layered two deep.

### ISSUE THREAD

**Issue by hmsommer** [gabelerner/canvg#407]
Canvg seems to have an issue when there is a tspan inside a tspan. I need to be able to code this so that I can have each word be a different font. (This is the only way to do this with the d3 and d3plus libraries I'm using)

Error I am getting:
Uncaught TypeError: parent.renderChild is not a function
(on line 2188 -> "parent.renderChild(ctx, child, i);")

Sample code:

```
<text id="practice-makes-perfect" class="wrap" y="110" x="210" font-size="39px" text-anchor="middle" style="font-size: 39px;" transform="rotate(0, 710, 610)translate(0,-8.580000000000002)">
<tspan x="210px" dx="215px" dy="42.900000000000006px" dominant-baseline="alphabetic" style="baseline-shift: 0%;">
<tspan class="amatic" fill="#F5F5EA" style="font-family: 'Amatic SC', cursive;"> José</tspan>
</tspan>
</text>
```
What it looks like when it renders:
svg: (what it is supposed to look like)

![image](https://cloud.githubusercontent.com/assets/6334481/10400782/10b6bb96-6e78-11e5-84e1-80579db65bb9.png)

What it looks like rendered by Canvg:
<img width="363" alt="screen shot 2015-10-09 at 11 26 31 am" src="https://cloud.githubusercontent.com/assets/6334481/10401236/f0815be4-6e7a-11e5-9b7e-016efa948963.png">

the dx attribute on the tspan seems to have been removed?

**Comment by bioinfornatics** [comment]
I got the same problem :+1:
