### ISSUE TITLE
Styles are not being used

### ISSUE THREAD

**Issue by mato75** [gabelerner/canvg#414]
I add <style> to svg, but when used with this library the styles are not applied. 

This example works great for Chrome and Firefox, http://techslides.com/save-svg-as-an-image, but IE and Safari have issues. Now I am trying to use this library, but with no luck. The styles are not applied.

**Comment by thelordgabo** [comment]
I also have the same problem.

**Comment by thelordgabo** [comment]
The styles, css rules are not applied.

**Comment by gabelerner** [comment]
all styles have to be internal the svg element using a `<style>` tag, and even then, only a subset are supported.  this project won't ever support downloading css or querying the page css
