### ISSUE TITLE
canvg handle svg error with width 100%

### ISSUE THREAD

**Issue by yangpu** [gabelerner/canvg#415]
<svg width='100%' height='100%'></svg>

canvg throw an error as:
Uncaught TypeError: Cannot read property 'width' of undefined

canvg works fine for <svg width='400' height='400'></svg>

**Comment by gabelerner** [comment]
please reopen issue w/ exact code/svg string you're running

**Comment by xmakina** [comment]
I'm getting the same issue. Here's the bits I think you'll need.

Element: <svg width="100%" height="24px"><g><path class="line" d="M0,19.621505047735003L11.076923076923077,17.75003046411946L22.153846153846153,17.646184088193557L33.23076923076923,18.45441338897004L44.30769230769231,24L55.38461538461539,3.071155916932292L66.46153846153847,7.317499492122048L77.53846153846153,5.541097261316634L88.61538461538461,7.81419240933304L99.6923076923077,13.024563319698544L110.76923076923077,5.331545041905942L121.84615384615384,0L132.92307692307693,3.1390952287648117"></path></g></svg>

Error: TypeError: Cannot read property 'width' of undefined
Error line: this.width=function(){return this.Current().width}

Let me know if you need anything else.
