### ISSUE TITLE
Microsoft Edge fails most tests.

### ISSUE THREAD

**Issue by evpozdniakov** [gabelerner/canvg#416]
Just check few tests from the beginning:
http://gabelerner.github.io/canvg/examples/index.htm

**Comment by adam187** [comment]
+1

**Comment by p0wdrdotcom** [comment]
+1

**Comment by p0wdrdotcom** [comment]
It appears that SVG's that use viewbox (half the reason why SVG is awesome) appear black in MS Edge

**Comment by jcvandan** [comment]
Does nobody have any update on this? It looks to me as if it could be an issue with Edge's implementation of Canvas. I am going to investigate this issue and see if I can reproduce the problem reliably.

**Comment by jcvandan** [comment]
I have submitted a pull request which fixes the problem of MS Edge rendering everything black, see #433

**Comment by gabelerner** [comment]
i see the lowercase issue/PR ... is there a place where i can easily test with edge to see if i can push this through or do i need to grab a VM and download it?

**Comment by p0wdrdotcom** [comment]
I've raised a pull req to sort out the upper case style tags for Edge
https://github.com/gabelerner/canvg/pull/440

**Comment by gabelerner** [comment]
i'll keep this open, can somebody with MS Edge test master and see if it's working?

**Comment by mihajul** [comment]
It's working on MS Edge 25.105786.0.0

**Comment by gabelerner** [comment]
Good enough for me ... I'll make a release sometime this week

**Comment by bernardwolff** [comment]
Broken again in Edge 38.14393.0.0
