### ISSUE TITLE
Why convert <image> does not work?

### ISSUE THREAD

**Issue by ravend7** [gabelerner/canvg#420]
Hi!

The resulting image can not be downloaded

work:
http://jsfiddle.net/L3hondLn/301/

don't work:
http://jsfiddle.net/L3hondLn/300/

**Comment by gabelerner** [comment]
the first issue is waiting for the image to be loaded, so you need to use the callback option

then, chrome won't let you call toDataUrl on a canvas that has an image, unless the image is downloaded via CORS, but w3.org won't let you do that

see errors in console in http://jsfiddle.net/L3hondLn/389/

if you reupload the image somewhere else that supports CORS using same code, then it'll start working.

alternatively, if the image is on the same domain as the script, get rid of `useCORS: true` and it'll work
