### ISSUE TITLE
area under the graph is painted with black

### ISSUE THREAD

**Issue by thelordgabo** [gabelerner/canvg#422]
Hi all, 
I have the following issue the area under some lines is painted with black, for more detail I attached an image.
![wrong-image](https://cloud.githubusercontent.com/assets/3825673/12099024/28f3084a-b2fc-11e5-9523-e1060322b330.PNG)

**Comment by fdasfdfasdf** [comment]
This happens because the library has problems interpreting css files.
A workaround is to set the "fill"-property to "none" manually via JavaScript/jQuery

**Comment by thelordgabo** [comment]
Thanks @fdasfdfasdf that works! but I have to do one more step, get rid of of the area painted with black of the chart and the subchart:

//revoming the fill of the main chart
$(".c3-chart")[0].style.cssText = "fill: none;";
//removing the fill of the subchart
$(".c3-chart")[1].style.cssText = "fill: none;";

**Comment by gabelerner** [comment]
we will probably never have full css support and only support a subset of it inline. going to close for now as you found a solution.

**Comment by Seankps** [comment]
I found the cause to be <font> tags in my svg. By adding styles to those tags (background-color: transparent; fill: none;) I was able to fix my black background without making the text invisible
