### ISSUE TITLE
Cleaning up after conversion

### ISSUE THREAD

**Issue by Tolmark12** [gabelerner/canvg#428]
Is there any way to clean up all the items used to generate an image? I took a heap snapshot and noticed that there is a detached canvas element. If a cleanup function isn't in place, I'm game to help.

**Comment by Tolmark12** [comment]
Nevermind, after crawling through the code, it looks like canvg cleans up everything, the leftover was coming from somewhere else

**Comment by gabelerner** [comment]
going to close this per last comment, please reopen if you still have an issue
