### ISSUE TITLE
May be it is much more complicated?????

### ISSUE THREAD

**Issue by GildoMat** [gabelerner/canvg#430]
Hi! I tryed to use your sample... [](([](http://gabelerner.github.io/canvg/examples/index.htm))) I have submitted one big svg xml into the "use your own" box but after some time, on the svg area appears the image, and in the canvas nothing .... do you know why? this is the svg text:

see the text file for the svg draw

**Comment by gabelerner** [comment]
no attachment here? please attach and reopen
