### ISSUE TITLE
Minification error caused by regular expresson

### ISSUE THREAD

**Issue by jcvandan** [gabelerner/canvg#431]
ASP.NET minfication library gives an error when trying to minify the canvg script. The problem which is causing an error is on line 144 the regular expresson `/{[^]*/gm`.

I have [checked on regex101](https://regex101.com/r/dU0dB4/1) and it seems like this regex is acceptable in the Javascript regex engine but not in others. If you go choose either the PHP or Python engines it is not a valid regex.

In the source code near this expression (line 124) is the following comment:

`// slightly modified version of https://github.com/keeganstreet/specificity/blob/master/specificity.js`

If you follow that link and view line 88 you will see the corresponding use of the problematic regular expression, and it states that it's purpose is to `Remove anything after a left brace in case a user has pasted in a rule, not just a selector`. You guys may be able to work this out from the regex itself but it's always been a bit of an arcane art to me :).

I understand that this is not a bug with canvg and the problem lies with the minification tool I am using, but I figure if the regex is tweaked and it does the same thing then please could it be merged in as it will save me running a mirrored repo. I am also going to look into the issues with Edge drawing black SVG's next so it would help if I can work on the main repo for that too.

If the regex is changed so a wildcard goes in the character search like so `/{[^*]*/gm` then it is valid in the other regex engines on regex101, see the following link: https://regex101.com/r/nU8sY7/1

I am going to make this change and do a pull request. Please feel free to shout at me for my dodgy regex skills but that change does seem to do the trick.

**Comment by gabelerner** [comment]
if it's valid JS, i would expect the asp.net minifier to be fixed, or make a PR on specificity repo and i'll pull in their changes if applied.  i want to be in sync with that library here to ensure all the same use cases are covered.
