### ISSUE TITLE
Synchronous  xhr deprecated

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [gabelerner/canvg#449]
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

I get this warning using it on Opera 35 (Chromium 48) and Chromium 50. And I'm using it to use an svg as badgeIcon.

Is that normal, and is there anything to do with it?

**Comment by holmberd** [comment]
It depends on how you supply the svg as a parameter. If you supply the SVG as and URL or dataUrl you will get the message you describe.

```
canvg(target, s)
	// empty parameters: replace all 'svg' elements on page with 'canvas' elements
	// target: canvas element or the id of a canvas element
	// s: svg string, url to svg file, or xml document
```

It arises from the function described below. Especially where the async flag is set to false, causing the script to try and fetch the url synchronously.

```
		svg.ajax = function(url) {
			var AJAX;
			if(window.XMLHttpRequest){AJAX=new XMLHttpRequest();}
			else{AJAX=new ActiveXObject('Microsoft.XMLHTTP');}
			if(AJAX){
			   AJAX.open('GET',url,false);
			   AJAX.send(null);
			   return AJAX.responseText;
			}
			return null;
		}
```

Cheers

**Comment by ZatsuneNoMokou** [comment]
So, I'll use xhr to get the file data in async way, and use canvg after

**Comment by holmberd** [comment]
Yes, that will probably work better for you, and you should serialize the svg subtree into a string to pass to canvg.

```
	var svg = document.getElementById(svg_id);
	var xml = new XMLSerializer().serializeToString(svg);
```
Something to read:
http://stackoverflow.com/questions/5201782/accessing-the-svg-data-through-javascript
http://svgopen.org/2010/papers/62-From_SVG_to_Canvas_and_Back/

**Comment by ZatsuneNoMokou** [comment]
The thing is, I don't use an html file on the background page, so I would have to insert the svg in the page, wait it to load, and do that after, I'm not sure of it. And I don't know how to insert an svg in javascript.

**Comment by holmberd** [comment]
I don't understand your problem, could you explain your situation with more information? Are you fetching the SVG from an external server?

**Comment by ZatsuneNoMokou** [comment]
No, the file is locale, I just prefer using url instead of putting svg code for code lisibility
