### ISSUE TITLE
SemiColons in Style Element

### ISSUE THREAD

**Issue by EdwinRoestenburg** [gabelerner/canvg#450]
CanVG doesn't accept semicolons between different styles in the Style Element.
A quick fix is the following:
In function:	svg.Element.style = function(node) {
After:	 	var cssDefs = css.split('}');

			// FIX START
			for (var i = 0; i < cssDefs.length; i++) {
				if (cssDefs[i].charAt(0) == ";") {
					cssDefs[i] = cssDefs[i].substring(1);
				}
			}
			// FIX END

**Comment by gabelerner** [comment]
what's the svg string so i can confirm that there's a bug?

**Comment by EdwinRoestenburg** [comment]
On 4/7/2016 3:23, Gabe Lerner wrote:
>
> what's the svg string so i can confirm that there's a bug?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/gabelerner/canvg/issues/450#issuecomment-206644149>
>


In reply to the above, please find two SVGs below.
Both are generated by FusionCharts.

I'm quite pleased with your tool b.t.w. !!

Explanation:
you code splits the style element on '}'
Using the styles element from the svgs below we then get:
     .fusion.....333333;
     ;.fusion.......666666;
etc.
The second line above causes problems, as it is not a style element due 
to the starting semicolon.
In a simpeler form:
<style>
     .x {}; .y {}
</style>


_*Here's the first SVGString.*__*
*_The bit in RED has been crippled for this email (I simple cut a large 
chunk out) as it contained sensitive data.


<svg xmlns:xlink=\"http://www.w3.org/1999/xlink\" 
xmlns=\"http://www.w3.org/2000/svg\"  id=\"raphael-paper-11\" 
style=\"top: -0.39px; overflow: hidden; position: relative; cursor: 
default; -ms-user-select: none; background-color: rgba(255, 255, 255, 
1); -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-user-select: 
none; -moz-user-select: -moz-none; user-select: none; 
-khtml-user-select: none; -o-user-select: none;\" width=\"1732\" 
height=\"600\" version=\"1.1\" >

*<style type=\"text/css\">.fusioncharts-legend .fusioncharts-caption { 
text-anchor: middle;fontFamily: Helvetica Neue,Arial;fontSize: 
9px;color: #333333;fontWeight: bold;lineHeight: 
10.799999999999999px;fill: #333333; };.fusioncharts-legend 
.fusioncharts-legenditem { fontFamily: Helvetica Neue,Arial;fontSize: 
10px;color: #666666;fontWeight: normal;lineHeight: 12px;fill: #666666; 
};.fusioncharts-caption { fontFamily: Helvetica Neue,Arial;color: 
#333333;fontSize: 14px;fontWeight: bold;lineHeight: 16.8px;fill: 
#333333; };.fusioncharts-subcaption { fontFamily: Helvetica 
Neue,Arial;color: #333333;fontSize: 14px;fontWeight: normal;lineHeight: 
16.8px;fill: #333333; }</style>*

<defs /><g class=\"raphael-group-12-background\"><rect style=\"fill: 
#ffffff; fill-opacity: 0.5; stroke: none;\" fill=\"#ffffff\" 
fill-opacity=\"0.5\" stroke=\"none\" x=\"0\" y=\"0\" width=\"1732\" 
height=\"600\" rx=\"0\" ry=\"0\" />
<rect style=\"fill: none; stroke: #767575; stroke-opacity: 0.5;\" 
fill=\"none\" stroke=\"#767575\" stroke-dasharray=\"none\" 
stroke-opacity=\"0.5\" stroke-width=\"0\" x=\"0\" y=\"0\" width=\"1732\" 
height=\"600\" rx=\"0\" ry=\"0\" /></g>
.......
.......
style=\"font-family: verdana,sans; font-size: 9px; cursor: pointer; 
fill: #000000; fill-opacity: 0.5; stroke: none; text-anchor: start;\" 
fill=\"#000000\" fill-opacity=\"0.5\" stroke=\"none\" 
text-anchor=\"start\" x=\"6\" y=\"596\"><tspan x=\"6\" dy=\"596\" 
xmlns:xml=\"http://www.w3.org/XML/1998/namespace\" 
xml:space=\"preserve\"> </tspan></text></svg>




_*Here's the second SVGString.*__*
*_This one has not been changed other then the added newlines to 
separate the style element.
It's an empty graph, but that's besides the point.


<svg xmlns:xlink=\"http://www.w3.org/1999/xlink\" 
xmlns=\"http://www.w3.org/2000/svg\"  id=\"raphael-paper-11\" 
style=\"top: -0.39px; overflow: hidden; position: relative; cursor: 
default; -ms-user-select: none; background-color: rgba(255, 255, 255, 
1); -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-user-select: 
none; -moz-user-select: -moz-none; user-select: none; 
-khtml-user-select: none; -o-user-select: none;\" width=\"1732\" 
height=\"600\" version=\"1.1\" >

<style type=\"text/css\">.fusioncharts-legend .fusioncharts-caption { 
text-anchor: middle;fontFamily: Helvetica Neue,Arial;fontSize: 
9px;color: #333333;fontWeight: bold;lineHeight: 
10.799999999999999px;fill: #333333; };.fusioncharts-legend 
.fusioncharts-legenditem { fontFamily: Helvetica Neue,Arial;fontSize: 
10px;color: #666666;fontWeight: normal;lineHeight: 12px;fill: #666666; 
};.fusioncharts-caption { fontFamily: Helvetica Neue,Arial;color: 
#333333;fontSize: 14px;fontWeight: bold;lineHeight: 16.8px;fill: 
#333333; };.fusioncharts-subcaption { fontFamily: Helvetica 
Neue,Arial;color: #333333;fontSize: 14px;fontWeight: normal;lineHeight: 
16.8px;fill: #333333; }</style>

<defs /><g class=\"raphael-group-12-background\"><rect style=\"fill: 
#ffffff; fill-opacity: 0.5; stroke: none;\" fill=\"#ffffff\" 
fill-opacity=\"0.5\" stroke=\"none\" x=\"0\" y=\"0\" width=\"1732\" 
height=\"600\" rx=\"0\" ry=\"0\" /><rect style=\"fill: none; stroke: 
#767575; stroke-opacity: 0.5;\" fill=\"none\" stroke=\"#767575\" 
stroke-dasharray=\"none\" stroke-opacity=\"0.5\" stroke-width=\"0\" 
x=\"0\" y=\"0\" width=\"1732\" height=\"600\" rx=\"0\" ry=\"0\" /></g><g 
class=\"raphael-group-22-axisbottom\"><g 
class=\"raphael-group-24-axis-lines\"><path style=\"fill: #eeeeee; 
fill-opacity: 0.5; stroke: #717170; stroke-opacity: 1;\" 
fill=\"#eeeeee\" fill-opacity=\"0.5\" stroke=\"#717170\" 
stroke-opacity=\"1\" stroke-width=\"2\" d=\"\" /><path style=\"fill: 
none; stroke: #000000; stroke-opacity: 0;\" fill=\"none\" 
stroke=\"#000000\" stroke-opacity=\"0\" stroke-width=\"0.1\" d=\"\" 
/><path style=\"fill: none; stroke: #999999; stroke-opacity: 1;\" 
fill=\"none\" stroke=\"#999999\" stroke-opacity=\"1\" stroke-width=\"1\" 
d=\"\" /><path style=\"fill: none; stroke: #999999; stroke-opacity: 1;\" 
fill=\"none\" stroke=\"#999999\" stroke-opacity=\"1\" stroke-width=\"1\" 
d=\"\" /><path style=\"fill: none; stroke: #999999; stroke-opacity: 1;\" 
fill=\"none\" stroke=\"#999999\" stroke-opacity=\"1\" stroke-width=\"1\" 
d=\"\" /><path style=\"fill: none; stroke: #999999; stroke-opacity: 1;\" 
fill=\"none\" stroke=\"#999999\" stroke-opacity=\"1\" stroke-width=\"1\" 
d=\"\" /><path style=\"fill: none; stroke: #999999; stroke-opacity: 1;\" 
fill=\"none\" stroke=\"#999999\" stroke-opacity=\"1\" stroke-width=\"1\" 
d=\"\" /><path style=\"fill: none; stroke: #717170; stroke-opacity: 
0.4;\" fill=\"none\" stroke=\"#717170\" stroke-opacity=\"0.4\" 
stroke-width=\"1\" d=\"M 0 0\" /></g><g 
class=\"raphael-group-25-axis-labels\" /></g><g 
class=\"raphael-group-13-dataset\"><g 
class=\"raphael-group-19-connectors\" stroke-width=\"100\" 
transform=\"matrix(1 0 0 1 0 0)\" /><g 
class=\"raphael-group-20-anchors\" /></g><g 
class=\"raphael-group-23-axistop\" /><g 
class=\"raphael-group-18-datalabels\" transform=\"matrix(1 0 0 1 0 0)\" 
/><g class=\"fusioncharts-legend\" transform=\"matrix(1 0 0 1 826.5 
560.5)\"><rect style=\"fill: #ffffff; fill-opacity: 0; stroke: #545454; 
stroke-opacity: 0;\" fill=\"#ffffff\" fill-opacity=\"0\" 
stroke=\"#545454\" stroke-opacity=\"0\" stroke-width=\"1\" x=\"0\" 
y=\"0\" width=\"80\" height=\"25\" rx=\"0\" ry=\"0\" /><text 
class=\"fusioncharts-legenditem\" font-size=\"10px\" style=\"font-size: 
10px; cursor: pointer; fill: #666666; stroke: none; text-anchor: 
start;\" fill=\"#666666\" stroke=\"none\" text-anchor=\"start\" x=\"23\" 
y=\"6.5\"><tspan x=\"23\" dy=\"9.3\">Cumulatief</tspan></text><path 
style=\"cursor: pointer; fill: #999999; fill-opacity: 1; stroke: 
#c2c2c2;\" fill=\"#999999\" fill-opacity=\"1\" stroke=\"#c2c2c2\" 
stroke-width=\"0.5\" d=\"M 7 7 L 18 7 L 18 18 L 7 18 Z\" /><rect 
style=\"cursor: pointer; fill: #c0c0c0; fill-opacity: 1e-006; stroke: 
none;\" fill=\"#c0c0c0\" fill-opacity=\"1e-006\" stroke=\"none\" 
stroke-width=\"1\" x=\"4\" y=\"4\" width=\"70\" height=\"17\" rx=\"0\" 
ry=\"0\" /></g><g class=\"raphael-group-39-caption\"><text 
class=\"fusioncharts-caption\" font-family=\"Helvetica Neue,Arial\" 
font-size=\"14px\" font-weight=\"bold\" style=\"font-family: helvetica 
neue,arial; font-size: 14px; font-weight: bold; fill: #333333; stroke: 
none; text-anchor: middle;\" fill=\"#333333\" stroke=\"none\" 
text-anchor=\"middle\" x=\"866\" y=\"15\"><tspan x=\"866\" 
dy=\"13.03\">Test TimeLimited (24 hours)</tspan></text><text 
class=\"fusioncharts-subcaption\" font-family=\"Helvetica Neue,Arial\" 
font-size=\"14px\" font-weight=\"normal\" style=\"font-family: helvetica 
neue,arial; font-size: 14px; font-weight: normal; fill: #333333; stroke: 
none; text-anchor: middle;\" fill=\"#333333\" stroke=\"none\" 
text-anchor=\"middle\" x=\"866\" y=\"34\"><tspan x=\"866\" 
dy=\"13.03\">28 mrt 2016 (RDD_Test)</tspan></text></g><g 
class=\"raphael-group-14-hot\"><g class=\"raphael-group-21-trackers\" 
/></g><g class=\"raphael-group-17-buttons\" /><text 
font-family=\"Verdana,sans\" font-size=\"9px\" style=\"font-family: 
verdana,sans; font-size: 9px; cursor: pointer; fill: #000000; 
fill-opacity: 0.5; stroke: none; text-anchor: start;\" fill=\"#000000\" 
fill-opacity=\"0.5\" stroke=\"none\" text-anchor=\"start\" x=\"6\" 
y=\"596\"><tspan x=\"6\" dy=\"596\" 
xmlns:xml=\"http://www.w3.org/XML/1998/namespace\" 
xml:space=\"preserve\"> </tspan></text></svg>"

**Comment by gabelerner** [comment]
i don't think it's valid css to have a semicolon between rules. try the following
```css
.test1 { color: black; }; .test2 { color: red; }
```
on http://www.css-validator.org/validator ... it fails

**Comment by EdwinRoestenburg** [comment]
Ah, that would mean that FusionChart creates invalid CSS.
I shall see if I can get them to change that.

Thanks,

Edwin Roestenburg.
