### ISSUE TITLE
labels behind cart / chart too wide

### ISSUE THREAD

**Issue by jjhii** [gabelerner/canvg#452]
I have a d3 chart that is being rendered and I am attempting to convert it to PNG using canvg.  In the browser the cart fills the left side and the labels are on the right side.  When I convert to PNG the cart is much wider and the labels are behind the chart.  I have a JSFiddle view, link below.  Any suggestions on fixing it?

http://jsfiddle.net/46bv10db/5/

I opened a stackoverflow issue here: 
http://stackoverflow.com/questions/36609398/when-printing-with-canvg-the-cart-labels-are-behind-the-chart

Thanks for any help!

**Comment by jjhii** [comment]
Ok, fixed the problem.  Not sure if it is something that needs fixed canvg or not so I will leave it here.

I changed the out put on the D3 charts to use matrix instead of x,y,width,height.

**Comment by gabelerner** [comment]
yea it looks fine in canvg so export to png should be pixel for pixel
